Embedding images and video
jstloyal/youtube_video_page pull request #1
Opened 2020-02-18 21:57 UTC by jstloyal

Created a youtube like website with video and some images embedded in it.

2020-02-19 00:05 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @jstloyal  and @harshdeepkanhai :balloon:  :lollipop: 

### The effort you put in your project is remarkable :muscle: but there is still some work to do to make it look more like the original :construction: :construction_worker_man: 

## Page Structure

**Navbar**

- [x] The navbar should be smaller, all the icons in the navbar should be smaller including the logo, the search bar should be wider and the background color should be white.

- Yours

![image](https://user-images.githubusercontent.com/52209067/74787854-cfd95700-5275-11ea-9b0b-74ed4de4cf72.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74787904-e97a9e80-5275-11ea-935c-8be4e65b63af.png)

**Video**

* [x] It shows the number of views
* [x] It has like and dislike icons (yours is missing the dislike button)
* [x] the Share should be a link or a button and the background should be white
* [x] It shows the avatar of the user who uploaded the video (The Avatar should be an image)
* [x] It has a subscribe button (the Subscribe should be a red button)

- Yours

![image](https://user-images.githubusercontent.com/52209067/74788279-f0ee7780-5276-11ea-8e32-c90f5e0ee4cf.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74788306-04014780-5277-11ea-976d-a4c7499273f1.png)

**Sidebar Recommended videos**

* [x] It shows the title of the video ( Please put titles of real videos don't use meaningless text unless is specified in the project description)  
* [x] It shows the number of views (put an actual number of views don't use meaningless text unless is specified in the project description) 
* [x]  the title and views have to be at the right of each thumbnail and not below them

- Yours

![image](https://user-images.githubusercontent.com/52209067/74788642-f9937d80-5277-11ea-856e-c461fe151ad7.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74788666-0ca64d80-5278-11ea-91f7-165bea10def4.png)

## Generals

**Readme**

- [x]  remove all the template instructions and also remove the empty sections or  add info to them, I have put comments on your code where changes should be made :arrow_double_down: 

**Inline styling**

- [x] remove all the inline styling I have spotted in your code as all styling should live in the CSS file :arrow_double_down: 

[OPTIONAL] I strongly encourage the use of the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links (navbar)

### That's it! :raised_hands: 

### Please :pray:  do the changes :memo:  and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist: 

Any question? reach to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-02-19 00:05 UTC, euqueme commented on README.md
> +![screenshot](./app_screenshot.png)
There is no such image called **app_screenshot.png** in your project, please upload the image or remove it from the Readme file

2020-02-19 00:05 UTC, euqueme commented on README.md
> +### Deployment
Add information to each title from line #25 to line #35 or delete them from your Readme file

2020-02-19 00:05 UTC, euqueme commented on README.md
> +- etc
remove `- etc` on line #65

2020-02-19 00:05 UTC, euqueme commented on README.md
> +To get a local copy up and running follow these simple example steps.
specify the steps or remove line #23 from your Readme file

2020-02-19 00:05 UTC, euqueme commented on README.md
> +**Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the currect project doesn't require testing.**
delete the instructions to use the Readme template (line #20 and #21)

2020-02-19 00:05 UTC, euqueme commented on README.md
> +Additional description about the project and its features.
delete this line #7

2020-02-19 00:05 UTC, euqueme commented on index.html
> +        <img src="img/youtubelogo.jpeg" style="width: 100px;" />
all the styling should be declared in the CSS file, remove the style for your image on line #10

2020-02-19 00:05 UTC, euqueme commented on index.html
> +          <img src="img/notify.jpeg" alt="Notifications" style="width: 50px;" />
all the styling should be declared in the CSS file, remove the style for your images on lines #22, #23 and #24

2020-02-19 20:33 UTC, addod19 requested changes
## Status: 

Hi @jstloyal and @harshdeepkanhai you have done a great job 👍 Making changes requested by previous reviewer. 🙂 
- You made changes to the video section 👍 But the subscribe button is currently not a button. Kindly fix it
[OPTIONAL]
Currently, the sidebar does not look good. We can make it look better 😄 

Kindly make these changes and submit another code review 🎈 
Happy coding 💻 
Daniel Larbi Addo

2020-02-19 21:02 UTC, jstloyal commented
I've made the changes!

2020-02-20 14:58 UTC, merged

2020-02-20 19:08 UTC, euqueme reviewed
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @jstloyal and @harshdeepkanhai  :handshake: 

### Thank you for doing the changes requested by me and the previous reviewer :medal_sports: 

### I have only one change to ask you for the project to be approved because the previous reviewer didn't mention some changes as a follow-up of my review, I'm mentioning them bellow but setting them as optional :point_down: 

## General

- [ ] please fix the HTML errors and warnings detected by the validator as we can't approve projects that have HTML errors

![image](https://user-images.githubusercontent.com/52209067/74969312-f4524200-53e1-11ea-96b6-be2a8d6a283a.png)

## Video

- [ ] [OPTIONAL] the video has to be closer to the sidebar actually, it should be bigger in size, look at the original

- Yours 

![image](https://user-images.githubusercontent.com/52209067/74968678-d1735e00-53e0-11ea-9851-83c9bb2a36a6.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74968712-e5b75b00-53e0-11ea-8fef-6eaa408125d9.png)

## Sidebar Recommended Videos

- [ ] [OPTIONAL] the views should be aligned to the left, some of them are shifting, also add some margin on the right of this section because the description of the last video looks like its right in the border of the screen

- Yours

![image](https://user-images.githubusercontent.com/52209067/74968927-4d6da600-53e1-11ea-95b0-ffa369cde628.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74968954-5cecef00-53e1-11ea-8fea-6aeb6a24a848.png)

### That's it, team! :raised_hands: 

### Please :pray:  do the changes :memo: and submit back for a code review when you are done :rocket: 

Happy coding! :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES  :traffic_light:

2020-02-21 18:31 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-02-21 18:43 UTC, addod19 reviewed
## Status: Require changes 🔴

Hi @jstloyal and @harshdeepkanhai, nice work 👍 . For your project to be approved you need to meet the minimum requirements. Currently, we are failing markup errors as requested by the previous reviewer 🙂 .
![ma](https://user-images.githubusercontent.com/46388113/75061930-a1f44c80-54d9-11ea-8f45-d387e648165f.PNG)
 Kindly fix it and submit code review
[OPTIONAL]
```Video Section``` does not look good. There is no spacing between the main video and the video thumbnail. Check image for clarification
![ma1](https://user-images.githubusercontent.com/46388113/75062071-f992b800-54d9-11ea-82eb-0728cb58464b.PNG)

Happy coding 💻 
Daniel Larbi Addo

2020-02-21 20:16 UTC, pelzolga123 reviewed
Approved.

2020-02-21 20:16 UTC, pelzolga123 commented
## Hi Team,
## Approved, Congratulation :+1: 
You did all changes required previously. Go ahead and merge to master
_Goodluck in your next project_ *Happy coding*